config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'raiting' => 'static_pages#raiting'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resources :users do 
    resources :microposts do 
      resources :comments do
        resources :answers
      end  
    end
  end
 resources :likes
  
  resources :comments
  resources :microposts do
    resources :likes, controller: :likes
  end
  resources :users do 
    resources :comments
  end
  resource :instagram do
    resource :callback, only: [:show, :create]
  end

  namespace :api, defaults: {format: 'json'} do
    resources :users 
    get 'current_user' => 'users#current'
    resources :microposts do
      resources :likes, controller: :likes
      resources :comments, controller: :comments
    end
    resources :comments
    resource  :raiting
  end  
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
  Hello, world
  %nav
    %ul
      %li
        %a{:href => "http://sports.ru"} close

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "Рейтинг", raiting_path, id: "logo"
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Главная страница", root_path
        %li= link_to "Помощь",   help_path
        %li
          - if current_user
            %li= link_to "Участники", users_path
            %li= link_to "Выход", signout_path, id: "Sign out"
          - else

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = yield(:title)
      | Фотоконкурс
    = stylesheet_link_tag    'application', media: 'all', |
      'data-turbolinks-track' => true                     |
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = flash[:notice]
    = render 'layouts/header'
    .container
      = yield
    = render 'layouts/footer'